@file:Suppress("ktlint:standard:max-line-length")

package dev.jagoba.lostielauncher.content.strings

import dev.jagoba.lostielauncher.content.Strings

/**
 * Spanish, ported verbatim from `desktop/LostieLauncher/Content/Strings.cs`.
 *
 * The default, and the fallback when a persisted language is not a
 * defined member.
 */
internal object EspStrings : Strings {
    override val titleHome = "Inicio"
    override val titleGames = "Mis Juegos"
    override val titleLibrary = "Biblioteca"
    override val titleSettings = "Ajustes"
    override val titleFaqs = "Preguntas frecuentes"
    override val faqsSearchPlaceholder = "Buscar en las preguntas y respuestas..."
    override val faqsNoResults = "Sin resultados para tu búsqueda"
    override val btnOk = "Aceptar"
    override val btnYes = "Sí"
    override val btnNo = "No"
    override val btnDownload = "Descargar"
    override val btnDownloaded = "Descargado"
    override val btnPause = "Pausar"
    override val btnResume = "Reanudar"
    override val btnUpdate = "Actualizar"
    override val btnPlay = "Jugar"
    override val tooltipOpenFolder = "Abrir carpeta del juego"
    override val tooltipOpenHelp = "Abrir carpeta de ayuda"
    override val tooltipUninstall = "Desinstalar juego"
    override val tooltipRefresh = "Actualizar"
    override val folderNotFoundTitle = "Carpeta no encontrada"
    override val folderNotFoundMessage = "La carpeta del juego no se encontró. ¿Quieres reinstalar los archivos?"
    override val uninstallConfirmTitle = "Desinstalar juego"
    override val uninstallConfirmMessage = "¿Seguro que quieres desinstalar {0}? Las partidas guardadas y el registro de tiempo jugado no se perderán."
    override val uninstallNotFoundTitle = "Archivos no encontrados"
    override val uninstallNotFoundMessage = "No se encontraron los archivos del juego, pero se ha limpiado el registro de la lista."
    override val uninstallErrorTitle = "Error al desinstalar"
    override val uninstallErrorMessage = "No se pudieron borrar todos los archivos de {0}. El juego se ha quitado de tu lista, pero queda esto en el disco:\n\n{1}\n\n¿Quieres abrir su ubicación para borrarlo a mano?"
    override val uninstallBlockedTitle = "No se pudo desinstalar"
    override val uninstallBlockedMessage = "No se ha podido borrar ningún archivo de {0}, así que sigue instalado y en tu lista. Algo lo está bloqueando:\n\n{1}\n\nCierra los programas que puedan estar usándolo e inténtalo de nuevo. ¿Quieres abrir su ubicación?"
    override val uninstallGameRunningTitle = "El juego está abierto"
    override val uninstallGameRunningMessage = "Cierra {0} antes de desinstalarlo."
    override val uninstallMaybeRunningMessage = "Parece que {0} está en uso por otro programa (el propio juego, un antivirus o el explorador de archivos). Si lo desinstalas ahora es posible que queden archivos sin borrar. ¿Quieres continuar de todas formas?"
    override val updateAvailableTitle = "Actualización disponible"
    override val updateAvailableMessage = "Nueva versión {0} disponible. ¿Reiniciar para actualizar?"
    override val settingsGeneral = "General"
    override val settingsAppearance = "Apariencia"
    override val settingsAutoUpdate = "Actualizaciones automáticas"
    override val settingsLanguage = "Idioma"
    override val settingsDownloadDir = "Directorio de descargas"
    override val settingsTheme = "Tema"
    override val btnBrowse = "Examinar..."
    override val settingsCheckForUpdates = "Buscar actualizaciones del launcher"
    override val upToDateTitle = "Sin actualizaciones"
    override val upToDateMessage = "Ya tienes la última versión del launcher."
    override val updateCheckBusyTitle = "Descarga en curso"
    override val updateCheckBusyMessage = "No se pueden buscar actualizaciones mientras hay una descarga en curso. Espera a que termine e inténtalo de nuevo."
    override val updateCheckFailedTitle = "Error al buscar actualizaciones"
    override val updateCheckFailedMessage = "No se ha podido comprobar si hay actualizaciones. Revisa tu conexión e inténtalo de nuevo más tarde."
    override val changeDownloadDirTitle = "Cambiar directorio de descargas"
    override val changeDownloadDirMessage = "Si tienes juegos instalados, tendrás que moverlos manualmente a la nueva ruta o el launcher no los reconocerá. ¿Deseas continuar?"
    override val exitWarningTitle = "Salir del launcher"
    override val exitWarningDownloadMessage = "Hay una descarga en curso. Si sales ahora se detendrá, pero podrás reanudarla la próxima vez que abras el launcher. ¿Seguro que quieres salir?"
    override val exitWarningGameMessage = "Tienes un juego abierto. Si sales ahora no se guardará el tiempo jugado de esta sesión. ¿Seguro que quieres salir?"
    override val exitWarningBothMessage = "Hay una descarga en curso y un juego abierto. La descarga se detendrá (podrás reanudarla más tarde) y no se guardará el tiempo jugado de esta sesión. ¿Seguro que quieres salir?"
    override val libraryNoContent = "No disponible"
    override val gamesNoContent = "No tienes juegos instalados"
    override val gamesGoToLibrary = "Ir a la biblioteca"
    override val homeNews = "Novedades"
    override val homeNotifications = "Notificaciones"
    override val homeNoContent = "Sin contenido"
    override val downloadDialogTitle = "Confirmar descarga"
    override val downloadDialogPath = "Ruta de descarga"
    override val downloadDialogGameSize = "Tamaño"
    override val downloadDialogFreeSpace = "Espacio libre"
    override val downloadDialogViewPage = "Ver página del juego"
    override val downloadDialogNoDescription = "Sin descripción disponible."
    override val downloadDialogKey = "Clave para versiones especiales (opcional)"
    override val downloadKeyInvalidTitle = "Clave no válida"
    override val downloadKeyInvalidMessage = "El formato de la clave no es válido. Debe seguir el formato XXXX-XXXX-XXXX-XXXX-XXXX."
    override val downloadErrorTitle = "Error en la descarga"
    override val downloadErrorMessage = "No se pudo completar la descarga. Por favor, intenta más tarde. Si el problema persiste, escribe en #testeo-launcher en Discord."
    override val downloadPermissionDeniedTitle = "Permisos insuficientes"
    override val downloadPermissionDeniedMessage = "El launcher no tiene permisos para instalar el juego en la ruta de descarga elegida. Prueba a cambiar a otra ruta en Ajustes."
    override val btnCancel = "Cancelar"
    override val cancelDownloadConfirmTitle = "Cancelar descarga"
    override val cancelDownloadConfirmMessage = "¿Seguro que quieres cancelar la descarga? Se eliminarán los archivos parcialmente descargados."
    override val statusExtracting = "Descomprimiendo..."
    override val statusVerifying = "Comprobando integridad..."
    override val statusUninstalling = "Desinstalando..."
    override val gameExeNotFoundTitle = "Juego no encontrado"
    override val gameExeNotFoundMessage = "No se encontró el ejecutable del juego. Intenta reinstalarlo."
    override val hashMismatchTitle = "Error de integridad"
    override val hashMismatchMessage = "El archivo descargado está dañado o ha sido modificado. Por favor, intenta de nuevo. Si el problema persiste, escribe en #testeo-launcher en Discord."
    override val welcomeDialogTitle = "¡Bienvenido al Lostie Launcher!"
    override val welcomeDialogDescription = "Descarga, actualiza y juega tus títulos favoritos en un solo lugar. Simple, rápido y sin complicaciones.\n\nTu privacidad es importante. No recopilamos ninguna información ni dato de ningún tipo.\n\nEste proyecto es opensource. ¿Dudas sobre cómo funciona? Consulta el código fuente"
    override val welcomeDialogContinue = "Continuar"
    override val repositoryUrl = "https://github.com/jagobainda/LostieLauncher"
    override val specialVersionDialogTitle = "Cambiar a versión especial"
    override val specialVersionDialogDescription = "Al cambiar a una versión especial no se pierde nada, funciona como una actualización normal."
    override val specialVersionDialogKeyLabel = "Clave de versión especial"
    override val btnConfirm = "Confirmar"
    override val downloadKeyNotFoundTitle = "Clave no encontrada"
    override val downloadKeyNotFoundMessage = "No se ha encontrado una versión especial con esta clave. Comprueba la clave e inténtalo de nuevo."
    override val downloadKeyMismatchTitle = "Clave incorrecta"
    override val downloadKeyMismatchMessage = "La clave no corresponde a este juego."
    override val tooltipSwitchSpecialVersion = "Cambiar a versión especial"
    override val serverActionsUnavailableTitle = "Servidor en mantenimiento"
    override val serverActionsUnavailableMessage = "El servidor está en mantenimiento. Las descargas, actualizaciones y versiones especiales volverán en cuanto termine."
    override val offlineModeLabel = "Modo offline"
    override val serverMaintenanceNotificationTitle = "Servidor en mantenimiento"
    override val serverMaintenanceNotificationMessage = "El launcher está en modo offline. Puedes seguir viendo tus juegos instalados; las descargas y actualizaciones se reactivarán automáticamente cuando el servicio vuelva."
    override val homeContentUnavailable = "No se ha podido cargar el contenido"
    override val contentOutOfDateLabel = "Contenido desactualizado"
    override val contentOutOfDateMessage = "No se ha podido conectar con el servidor. Se muestra el último contenido conocido, que puede estar desactualizado."
    override val settingsGamesStoredIn = "Los juegos se guardan en:"
    override val settingsOneDriveWarning = "Esta carpeta la sincroniza OneDrive: los juegos ocuparán tu almacenamiento en la nube y pueden fallar al abrirse sin conexión. Es mejor elegir otra ubicación."
    override val oneDriveWarningTitle = "Carpeta sincronizada con OneDrive"
    override val oneDriveWarningMessage = "Esta carpeta la sincroniza OneDrive:\n\n{0}\n\nCada juego ocupa varios gigas, así que se subirían a tu almacenamiento en la nube, la sincronización competiría con las instalaciones y los archivos podrían quedarse solo en línea y no abrirse sin conexión.\n\n¿Quieres usarla de todas formas?"
    override val downloadDirNotUsableTitle = "Carpeta de descargas no válida"
    override val downloadDirNotUsableMessage = "El launcher no puede usar esta carpeta:\n\n{0}\n\nLa comprobación falló al {1}.\n\nElige otra carpeta en Ajustes."
    override val downloadDirStepCreate = "crear la carpeta"
    override val downloadDirStepWrite = "escribir un archivo de prueba"
    override val downloadDirStepRename = "renombrar un archivo de prueba (la carpeta permite escribir, pero no renombrar ni borrar)"
}
