package dev.jagoba.lostielauncher.ui.theme

import dev.jagoba.lostielauncher.model.AppTheme

/**
 * The desktop's palettes, exactly as the resource dictionaries in
 * `desktop/LostieLauncher/Themes/` write them: the XAML colour key, and the hex string with no conversion
 * applied. `PalettesTest` is what compares them to the production values, and
 * it parses these itself rather than reusing the production parser, so a bug in
 * the conversion cannot hide behind a test that shares it.
 */
internal val DesktopPalettes: Map<AppTheme, Map<String, String>> = mapOf(
    AppTheme.Volcarona to mapOf(
        "PrimaryBgColor" to "#4d4949",
        "SecondaryBgColor" to "#3a3737",
        "TertiaryBgColor" to "#2e2c2c",
        "PrimaryFgColor" to "#f08058",
        "PrimaryFgHoverColor" to "#d06038",
        "PrimaryFgPressedColor" to "#b04020",
        "SecondaryFgColor" to "#f3f7fa",
        "SecondaryFgDimColor" to "#88f3f7fa",
        "SuccessColor" to "#2e7d32",
        "OverlaySubtleColor" to "#1AFFFFFF",
        "OverlayLightColor" to "#22FFFFFF",
        "OverlayMutedColor" to "#33FFFFFF",
        "OverlayMediumColor" to "#55FFFFFF",
        "OverlayStrongColor" to "#88FFFFFF",
    ),
    AppTheme.Zoroark to mapOf(
        "PrimaryBgColor" to "#2c2933",
        "SecondaryBgColor" to "#211e2a",
        "TertiaryBgColor" to "#181620",
        "PrimaryFgColor" to "#c42d3f",
        "PrimaryFgHoverColor" to "#a82435",
        "PrimaryFgPressedColor" to "#8c1c2a",
        "SecondaryFgColor" to "#f5ede0",
        "SecondaryFgDimColor" to "#88f5ede0",
        "SuccessColor" to "#2e7d32",
        "OverlaySubtleColor" to "#1AFFFFFF",
        "OverlayLightColor" to "#22FFFFFF",
        "OverlayMutedColor" to "#33FFFFFF",
        "OverlayMediumColor" to "#55FFFFFF",
        "OverlayStrongColor" to "#88FFFFFF",
    ),
    AppTheme.Infernape to mapOf(
        "PrimaryBgColor" to "#4a3535",
        "SecondaryBgColor" to "#3a2828",
        "TertiaryBgColor" to "#2e1f1f",
        "PrimaryFgColor" to "#cf4f51",
        "PrimaryFgHoverColor" to "#b83a3c",
        "PrimaryFgPressedColor" to "#f2d848",
        "SecondaryFgColor" to "#f5e8d8",
        "SecondaryFgDimColor" to "#99f5e8d8",
        "SuccessColor" to "#2e7d32",
        "OverlaySubtleColor" to "#1AFFFFFF",
        "OverlayLightColor" to "#22FFFFFF",
        "OverlayMutedColor" to "#33FFFFFF",
        "OverlayMediumColor" to "#55FFFFFF",
        "OverlayStrongColor" to "#88FFFFFF",
    ),
    AppTheme.Torterra to mapOf(
        "PrimaryBgColor" to "#3a3020",
        "SecondaryBgColor" to "#2c2418",
        "TertiaryBgColor" to "#221c12",
        "PrimaryFgColor" to "#5a9e42",
        "PrimaryFgHoverColor" to "#447a30",
        "PrimaryFgPressedColor" to "#8bc34a",
        "SecondaryFgColor" to "#e8dcc8",
        "SecondaryFgDimColor" to "#99e8dcc8",
        "SuccessColor" to "#2e7d32",
        "OverlaySubtleColor" to "#1AFFFFFF",
        "OverlayLightColor" to "#22FFFFFF",
        "OverlayMutedColor" to "#33FFFFFF",
        "OverlayMediumColor" to "#55FFFFFF",
        "OverlayStrongColor" to "#88FFFFFF",
    ),
    AppTheme.Empoleon to mapOf(
        "PrimaryBgColor" to "#252e38",
        "SecondaryBgColor" to "#1c242d",
        "TertiaryBgColor" to "#141b22",
        "PrimaryFgColor" to "#3a82c4",
        "PrimaryFgHoverColor" to "#2a68a0",
        "PrimaryFgPressedColor" to "#6ab0e8",
        "SecondaryFgColor" to "#dce8f0",
        "SecondaryFgDimColor" to "#99dce8f0",
        "SuccessColor" to "#2e7d32",
        "OverlaySubtleColor" to "#1AFFFFFF",
        "OverlayLightColor" to "#22FFFFFF",
        "OverlayMutedColor" to "#33FFFFFF",
        "OverlayMediumColor" to "#55FFFFFF",
        "OverlayStrongColor" to "#88FFFFFF",
    ),
    AppTheme.Mewtwo to mapOf(
        "PrimaryBgColor" to "#342e4a",
        "SecondaryBgColor" to "#272238",
        "TertiaryBgColor" to "#1e1a2c",
        "PrimaryFgColor" to "#c060f0",
        "PrimaryFgHoverColor" to "#9040cc",
        "PrimaryFgPressedColor" to "#40e0d0",
        "SecondaryFgColor" to "#ede8ff",
        "SecondaryFgDimColor" to "#99ede8ff",
        "SuccessColor" to "#2e7d32",
        "OverlaySubtleColor" to "#1AFFFFFF",
        "OverlayLightColor" to "#22FFFFFF",
        "OverlayMutedColor" to "#33FFFFFF",
        "OverlayMediumColor" to "#55FFFFFF",
        "OverlayStrongColor" to "#88FFFFFF",
    ),
    AppTheme.Cefireon to mapOf(
        "PrimaryBgColor" to "#ffefd3",
        "SecondaryBgColor" to "#e8a772",
        "TertiaryBgColor" to "#ffefd3",
        "PrimaryFgColor" to "#3ecfcf",
        "PrimaryFgHoverColor" to "#343434",
        "PrimaryFgPressedColor" to "#f5e653",
        "SecondaryFgColor" to "#343434",
        "SecondaryFgDimColor" to "#88343434",
        "SuccessColor" to "#78c878",
        "OverlaySubtleColor" to "#1A000000",
        "OverlayLightColor" to "#22000000",
        "OverlayMutedColor" to "#33000000",
        "OverlayMediumColor" to "#55000000",
        "OverlayStrongColor" to "#88000000",
    ),
    AppTheme.Sylveon to mapOf(
        "PrimaryBgColor" to "#fde8f0",
        "SecondaryBgColor" to "#f0b0cc",
        "TertiaryBgColor" to "#fde8f0",
        "PrimaryFgColor" to "#5aaad8",
        "PrimaryFgHoverColor" to "#3888b8",
        "PrimaryFgPressedColor" to "#1868a0",
        "SecondaryFgColor" to "#3a2030",
        "SecondaryFgDimColor" to "#883a2030",
        "SuccessColor" to "#3aaa6a",
        "OverlaySubtleColor" to "#1A000000",
        "OverlayLightColor" to "#22000000",
        "OverlayMutedColor" to "#33000000",
        "OverlayMediumColor" to "#55000000",
        "OverlayStrongColor" to "#88000000",
    ),
    AppTheme.Astrem to mapOf(
        "PrimaryBgColor" to "#eef3ff",
        "SecondaryBgColor" to "#aec4ec",
        "TertiaryBgColor" to "#eef3ff",
        "PrimaryFgColor" to "#2255cc",
        "PrimaryFgHoverColor" to "#1844aa",
        "PrimaryFgPressedColor" to "#0f3388",
        "SecondaryFgColor" to "#141820",
        "SecondaryFgDimColor" to "#88141820",
        "SuccessColor" to "#3aaa6a",
        "OverlaySubtleColor" to "#1A000000",
        "OverlayLightColor" to "#22000000",
        "OverlayMutedColor" to "#33000000",
        "OverlayMediumColor" to "#55000000",
        "OverlayStrongColor" to "#88000000",
    ),
    AppTheme.Auretoskos to mapOf(
        "PrimaryBgColor" to "#3b3838",
        "SecondaryBgColor" to "#2b2929",
        "TertiaryBgColor" to "#1e1c1c",
        "PrimaryFgColor" to "#f0b020",
        "PrimaryFgHoverColor" to "#cc9010",
        "PrimaryFgPressedColor" to "#a87008",
        "SecondaryFgColor" to "#f0eded",
        "SecondaryFgDimColor" to "#88f0eded",
        "SuccessColor" to "#2e7d32",
        "OverlaySubtleColor" to "#1AFFFFFF",
        "OverlayLightColor" to "#22FFFFFF",
        "OverlayMutedColor" to "#33FFFFFF",
        "OverlayMediumColor" to "#55FFFFFF",
        "OverlayStrongColor" to "#88FFFFFF",
    ),
)
